package tn.com.catering.identity.config;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import tn.com.catering.identity.entities.Brand;
import tn.com.catering.identity.entities.Category;
import tn.com.catering.identity.entities.Product;
import tn.com.catering.identity.entities.ProductFormat;
import tn.com.catering.identity.entities.ProductImage;
import tn.com.catering.identity.repositories.BrandRepository;
import tn.com.catering.identity.repositories.CategoryRepository;
import tn.com.catering.identity.repositories.ProductRepository;

/**
 * Loads the initial catalogue from classpath:seed/catalog-seed.json.
 *
 * <p>The file is generated by {@code scripts/export-backend-seed.mjs}, which
 * joins the curated bilingual catalogue with the Vinto crawl snapshot to recover
 * prices, stock and supplier references. Regenerate it there rather than editing
 * it by hand.
 *
 * <p>The seeder only runs on an empty product table, so restarting the
 * application never overwrites an administrator's edits. To reseed, drop the
 * database file.
 */
@Component
public class CatalogSeeder implements ApplicationRunner {

    private static final Logger LOGGER = LoggerFactory.getLogger(CatalogSeeder.class);
    private static final String SEED_PATH = "seed/catalog-seed.json";

    private final ProductRepository products;
    private final CategoryRepository categories;
    private final BrandRepository brands;
    private final ObjectMapper objectMapper;
    private final boolean enabled;

    public CatalogSeeder(ProductRepository products, CategoryRepository categories, BrandRepository brands,
                         ObjectMapper objectMapper,
                         @Value("${app.catalog.seed-on-startup:true}") boolean enabled) {
        this.products = products;
        this.categories = categories;
        this.brands = brands;
        this.objectMapper = objectMapper;
        this.enabled = enabled;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) throws Exception {
        if (!enabled) return;
        if (products.count() > 0) {
            LOGGER.info("Catalogue already populated ({} products); seeding skipped.", products.count());
            return;
        }
        ClassPathResource resource = new ClassPathResource(SEED_PATH);
        if (!resource.exists()) {
            LOGGER.warn("No catalogue seed at classpath:{}. Run: node scripts/export-backend-seed.mjs", SEED_PATH);
            return;
        }

        SeedFile seed;
        try (InputStream in = resource.getInputStream()) {
            seed = objectMapper.readValue(in, SeedFile.class);
        }

        seed.categories().stream()
                .filter(row -> categories.findByExternalId(row.externalId()).isEmpty())
                .map(CatalogSeeder::toCategory)
                .forEach(categories::save);

        seed.brands().stream()
                .filter(row -> brands.findByExternalId(row.externalId()).isEmpty())
                .map(CatalogSeeder::toBrand)
                .forEach(brands::save);

        long priced = 0;
        for (SeedProduct row : seed.products()) {
            Product product = toProduct(row);
            if (product.getPrice() != null) priced++;
            products.save(product);
        }

        LOGGER.info("Catalogue seeded: {} products ({} priced, {} awaiting a price), {} categories, {} brands.",
                seed.products().size(), priced, seed.products().size() - priced,
                seed.categories().size(), seed.brands().size());
    }

    private static Category toCategory(SeedCategory row) {
        Category category = new Category(row.externalId(), row.slug(), row.nameFr());
        category.setNameEn(row.nameEn());
        category.setParentExternalId(row.parentExternalId());
        category.setAccent(row.accent());
        category.setImage(row.image());
        category.setIcon(row.icon());
        return category;
    }

    private static Brand toBrand(SeedBrand row) {
        Brand brand = new Brand(row.externalId(), row.slug(), row.name());
        brand.setLogo(row.logo());
        brand.setDescriptionFr(row.descriptionFr());
        brand.setDescriptionEn(row.descriptionEn());
        brand.setWebsite(row.website());
        return brand;
    }

    private static Product toProduct(SeedProduct row) {
        Product product = new Product(row.sourceId(), row.slug(), row.nameFr(), row.categoryId());
        product.setNameEn(row.nameEn());
        product.setShortDescriptionFr(row.shortDescriptionFr());
        product.setShortDescriptionEn(row.shortDescriptionEn());
        product.setDescriptionFr(row.descriptionFr());
        product.setDescriptionEn(row.descriptionEn());
        product.setSubcategoryId(row.subcategoryId());
        product.setBrandId(row.brandId());
        product.setIndustries(new LinkedHashSet<>(row.industries() == null ? List.of() : row.industries()));
        // Null stays null: a reference the company has not priced is published as
        // "prix sur demande" rather than given an invented figure.
        product.setPrice(row.price());
        product.setCurrency(row.price() == null ? null : (row.currency() == null ? "TND" : row.currency()));
        product.setStockQuantity(row.stockQuantity());
        product.setSupplierReference(row.reference());
        product.setSourceUrl(row.sourceUrl());
        product.setTechnicalSheetUrl(row.technicalSheetUrl());
        product.setFeatured(row.featured());
        product.setNeedsVerification(row.needsVerification());
        product.setSeoTitleFr(row.seoTitleFr());
        product.setSeoTitleEn(row.seoTitleEn());
        product.setSeoDescriptionFr(row.seoDescriptionFr());
        product.setSeoDescriptionEn(row.seoDescriptionEn());

        List<SeedImage> images = row.images() == null ? List.of() : row.images();
        for (int index = 0; index < images.size(); index++) {
            SeedImage image = images.get(index);
            product.addImage(new ProductImage(
                    image.src(),
                    image.altFr() == null ? row.nameFr() : image.altFr(),
                    image.altEn(),
                    image.width(), image.height(), index));
        }

        List<SeedFormat> formats = row.formats() == null ? List.of() : row.formats();
        for (int index = 0; index < formats.size(); index++) {
            SeedFormat format = formats.get(index);
            product.addFormat(new ProductFormat(
                    format.externalId(), format.value(), format.packQuantity(),
                    format.sizeBucket(), format.reference(), index));
        }
        return product;
    }

    // Seed shapes. Unknown properties are ignored so the exporter can add fields
    // without breaking startup; the application sets fail-on-unknown globally for
    // request bodies, which is a different and stricter concern.

    @JsonIgnoreProperties(ignoreUnknown = true)
    record SeedFile(List<SeedCategory> categories, List<SeedBrand> brands, List<SeedProduct> products) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record SeedCategory(String externalId, String slug, String nameFr, String nameEn,
                        String parentExternalId, String accent, String image, String icon) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record SeedBrand(String externalId, String slug, String name, String logo,
                     String descriptionFr, String descriptionEn, String website) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record SeedProduct(String sourceId, String slug, String nameFr, String nameEn,
                       String shortDescriptionFr, String shortDescriptionEn,
                       String descriptionFr, String descriptionEn,
                       String categoryId, String subcategoryId, String brandId,
                       List<String> industries, boolean featured, String technicalSheetUrl,
                       boolean needsVerification, String seoTitleFr, String seoTitleEn,
                       String seoDescriptionFr, String seoDescriptionEn,
                       BigDecimal price, String currency, Integer stockQuantity,
                       String reference, String sourceUrl,
                       List<SeedFormat> formats, List<SeedImage> images) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record SeedFormat(String externalId, String value, Integer packQuantity,
                      String sizeBucket, String reference) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record SeedImage(String src, String altFr, String altEn, Integer width, Integer height) {}
}
