package tn.com.catering.identity.config;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import tn.com.catering.identity.entities.Product;
import tn.com.catering.identity.entities.ProductFormat;
import tn.com.catering.identity.entities.ProductImage;
import tn.com.catering.identity.entities.SaleMode;
import tn.com.catering.identity.repositories.ProductRepository;

/**
 * Applies a catalogue reconciliation batch (classpath:seed/catalog-reconciliation.json)
 * to a database that already holds the catalogue.
 *
 * <p>{@link CatalogSeeder} only fills an empty table, so a correction to the
 * seed never reaches a live database on its own. This runner closes that gap,
 * in a single transaction, in two parts:
 *
 * <ol>
 *   <li><b>Structure</b> - new products and withdrawn records. It runs once:
 *       when every product it adds already exists it is skipped, so an
 *       administrator who later reactivates a withdrawn product is not
 *       overruled on the next restart.</li>
 *   <li><b>Content and supplier terms</b> - corrected names and formats,
 *       prices, sale lots, out-of-stock lines and the matched photographs of
 *       new products (never one an administrator uploaded). Every change is a
 *       compare-and-set against the value the batch was prepared from, so it is
 *       evaluated on every start: applied where the old value is still there, a
 *       no-op where the new one already is, and left alone (and logged) where an
 *       administrator has set something else.</li>
 * </ol>
 *
 * <p>Nothing is deleted: a withdrawn product is set {@code active=false}, so
 * carts and quotes that reference it keep their history. The photographs of
 * existing products are never touched.
 *
 * <p>The batch is generated by {@code frontend/scripts/export-catalog-reconciliation.mjs}.
 */
@Component
@Order(2)
public class CatalogReconciliationRunner implements ApplicationRunner {

    private static final Logger LOGGER = LoggerFactory.getLogger(CatalogReconciliationRunner.class);
    private static final String BATCH_PATH = "seed/catalog-reconciliation.json";
    /** Where the catalogue's own matched photographs of new products live. */
    private static final String CATALOGUE_IMAGE_PREFIX = "/img/products/catalogue/";

    private final ProductRepository products;
    private final ObjectMapper objectMapper;
    private final boolean enabled;

    public CatalogReconciliationRunner(ProductRepository products, ObjectMapper objectMapper,
                                       @Value("${app.catalog.reconcile-on-startup:true}") boolean enabled) {
        this.products = products;
        this.objectMapper = objectMapper;
        this.enabled = enabled;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) throws Exception {
        if (!enabled) return;
        ClassPathResource resource = new ClassPathResource(BATCH_PATH);
        if (!resource.exists()) return;
        Batch batch;
        try (InputStream in = resource.getInputStream()) {
            batch = objectMapper.readValue(in, Batch.class);
        }
        apply(batch);
    }

    /** Applies one batch. Package-visible so the integration test can drive it directly. */
    @Transactional
    Outcome apply(Batch batch) {
        if (products.count() == 0) {
            // An empty table is the seeder's job; a lone batch is not a catalogue.
            return Outcome.SKIPPED;
        }
        int structural = applyStructure(batch);
        int terms = applyTerms(batch);
        return structural < 0 && terms == 0 ? Outcome.ALREADY_APPLIED : Outcome.APPLIED;
    }

    /** Additions, corrections, deactivations. Returns -1 when already applied. */
    private int applyStructure(Batch batch) {
        List<CatalogSeeder.SeedProduct> additions = listOrEmpty(batch.additions());
        if (!additions.isEmpty() && additions.stream().allMatch(row -> products.existsBySourceId(row.sourceId()))) {
            LOGGER.info("Catalogue reconciliation {}: structure already applied.", batch.batch());
            return -1;
        }

        int added = 0;
        for (CatalogSeeder.SeedProduct row : additions) {
            if (products.existsBySourceId(row.sourceId())) continue;
            products.save(CatalogSeeder.toProduct(row));
            added++;
        }

        int deactivated = 0;
        for (Deactivation deactivation : listOrEmpty(batch.deactivations())) {
            Optional<Product> found = products.findBySourceId(deactivation.sourceId());
            if (found.isEmpty() || !found.get().isActive()) continue;
            Product product = found.get();
            if (!Objects.equals(product.getNameFr(), deactivation.expectedNameFr())) {
                LOGGER.warn("Reconciliation {}: {} was renamed to \"{}\" since the batch was prepared; left active.",
                        batch.batch(), deactivation.sourceId(), product.getNameFr());
                continue;
            }
            product.setActive(false);
            deactivated++;
        }

        LOGGER.info("Catalogue reconciliation {}: {} added, {} deactivated.", batch.batch(), added, deactivated);
        return added + deactivated;
    }

    /**
     * Corrections, supplier prices and lots, out-of-stock lines, matched
     * photographs: compare-and-set changes, evaluated on every start. Returns
     * the number of changes.
     */
    private int applyTerms(Batch batch) {
        int corrected = 0;
        for (Correction correction : listOrEmpty(batch.corrections())) {
            Optional<Product> found = products.findBySourceId(correction.sourceId());
            if (found.isEmpty()) continue;
            Product product = found.get();
            String format = product.getFormats().isEmpty() ? null : product.getFormats().get(0).getFormatValue();
            String targetFormat = listOrEmpty(correction.formats()).isEmpty() ? null : correction.formats().get(0).value();
            if (Objects.equals(product.getNameFr(), correction.nameFr()) && Objects.equals(format, targetFormat)) continue;
            boolean knownName = Objects.equals(product.getNameFr(), correction.expectedNameFr())
                    || Objects.equals(product.getNameFr(), correction.nameFr());
            boolean knownFormat = Objects.equals(format, correction.expectedFormatValue()) || Objects.equals(format, targetFormat);
            if (!knownName || !knownFormat) {
                LOGGER.warn("Reconciliation {}: {} now reads \"{}\" / \"{}\", changed since the batch was prepared; correction skipped.",
                        batch.batch(), correction.sourceId(), product.getNameFr(), format);
                continue;
            }
            correct(product, correction);
            corrected++;
        }

        int repriced = 0;
        for (Repricing repricing : listOrEmpty(batch.repricings())) {
            Optional<Product> found = products.findBySourceId(repricing.sourceId());
            if (found.isEmpty()) continue;
            Product product = found.get();
            if (hasTerms(product, repricing)) continue;
            if (!samePrice(product.getPrice(), repricing.expectedPrice())) {
                LOGGER.warn("Reconciliation {}: {} is priced {} (expected {} before, {} after); left unchanged.",
                        batch.batch(), repricing.sourceId(), product.getPrice(), repricing.expectedPrice(), repricing.price());
                continue;
            }
            if (reprice(product, repricing)) {
                repriced++;
            } else {
                LOGGER.warn("Reconciliation {}: {} pack price {} is not unitPrice × packQuantity; left unchanged.",
                        batch.batch(), repricing.sourceId(), repricing.price());
            }
        }

        int outOfStock = 0;
        for (StockReset reset : listOrEmpty(batch.unavailable())) {
            Optional<Product> found = products.findBySourceId(reset.sourceId());
            if (found.isEmpty() || Objects.equals(found.get().getStockQuantity(), 0)) continue;
            if (!Objects.equals(found.get().getStockQuantity(), reset.expectedStock())) continue;
            found.get().setStockQuantity(0);
            outOfStock++;
        }

        int imagesSet = 0;
        for (ImageSet imageSet : listOrEmpty(batch.imageSets())) {
            Optional<Product> found = products.findBySourceId(imageSet.sourceId());
            if (found.isEmpty()) continue;
            Product product = found.get();
            List<CatalogSeeder.SeedImage> target = listOrEmpty(imageSet.images());
            List<String> current = product.getImages().stream().map(ProductImage::getSrc).toList();
            if (current.equals(target.stream().map(CatalogSeeder.SeedImage::src).toList())) continue;
            // Only a product with no photograph, or with the catalogue's own
            // matched photographs, is (re)set. A photograph an administrator
            // uploaded lives elsewhere and is never replaced.
            if (!current.stream().allMatch(src -> src != null && src.startsWith(CATALOGUE_IMAGE_PREFIX))) continue;
            product.clearImages();
            for (int index = 0; index < target.size(); index++) {
                CatalogSeeder.SeedImage image = target.get(index);
                product.addImage(new ProductImage(image.src(), image.altFr() == null ? product.getNameFr() : image.altFr(),
                        image.altEn(), image.width(), image.height(), index));
            }
            imagesSet++;
        }

        int changes = corrected + repriced + outOfStock + imagesSet;
        if (changes > 0) {
            LOGGER.info("Catalogue reconciliation {}: {} corrected, {} repriced, {} out of stock, {} photograph sets updated.",
                    batch.batch(), corrected, repriced, outOfStock, imagesSet);
        }
        return changes;
    }

    /** True when the product already carries exactly the batch's sale terms. */
    private static boolean hasTerms(Product product, Repricing repricing) {
        List<CatalogSeeder.SeedFormat> formats = listOrEmpty(repricing.formats());
        Integer pack = formats.isEmpty() ? null : formats.get(0).packQuantity();
        return samePrice(product.getPrice(), repricing.price())
                && product.getSaleMode() == repricing.saleMode()
                && samePrice(product.isPackOnly() ? product.getUnitPrice() : null,
                        repricing.saleMode() == SaleMode.PACK_ONLY ? repricing.unitPrice() : null)
                && Objects.equals(product.getPackQuantity(), pack);
    }

    /**
     * Applies supplier sale terms: price, sale mode, unit price, unit and the
     * pack size on the primary format. False, and nothing changed, when a pack
     * price does not equal its unit price times its pack size.
     */
    private static boolean reprice(Product product, Repricing repricing) {
        List<CatalogSeeder.SeedFormat> formats = listOrEmpty(repricing.formats());
        if (repricing.saleMode() == SaleMode.PACK_ONLY) {
            Integer pack = formats.isEmpty() ? null : formats.get(0).packQuantity();
            BigDecimal expected = Product.packPrice(repricing.unitPrice(), pack);
            if (expected == null || !samePrice(expected, repricing.price())) return false;
        }
        replaceFormats(product, formats);
        product.setSaleMode(repricing.saleMode());
        product.setUnitPrice(repricing.saleMode() == SaleMode.PACK_ONLY ? repricing.unitPrice() : null);
        product.setUnitLabel(repricing.unitLabel());
        product.setPrice(repricing.price());
        product.setCurrency(repricing.price() == null ? null : "TND");
        if (repricing.reference() != null) product.setSupplierReference(repricing.reference());
        return true;
    }

    private static boolean samePrice(BigDecimal a, BigDecimal b) {
        return a == null ? b == null : b != null && a.compareTo(b) == 0;
    }

    private static void correct(Product product, Correction correction) {
        product.setNameFr(correction.nameFr());
        product.setNameEn(correction.nameEn());
        product.setShortDescriptionFr(correction.shortDescriptionFr());
        product.setShortDescriptionEn(correction.shortDescriptionEn());
        product.setDescriptionFr(correction.descriptionFr());
        product.setDescriptionEn(correction.descriptionEn());
        product.setSeoTitleFr(correction.seoTitleFr());
        product.setSeoTitleEn(correction.seoTitleEn());
        product.setSeoDescriptionFr(correction.seoDescriptionFr());
        product.setSeoDescriptionEn(correction.seoDescriptionEn());
        replaceFormats(product, listOrEmpty(correction.formats()));

        // The photographs stay; only their alt text carries the product name.
        List<ImageAlt> alts = listOrEmpty(correction.imageAlts());
        List<ProductImage> images = product.getImages();
        for (int index = 0; index < Math.min(alts.size(), images.size()); index++) {
            images.get(index).setAltFr(alts.get(index).altFr());
            images.get(index).setAltEn(alts.get(index).altEn());
        }
    }

    /**
     * Cart lines record the chosen format as text, not as a reference to these
     * rows, so replacing them cannot orphan anything.
     */
    private static void replaceFormats(Product product, List<CatalogSeeder.SeedFormat> formats) {
        product.clearFormats();
        for (int index = 0; index < formats.size(); index++) {
            CatalogSeeder.SeedFormat format = formats.get(index);
            product.addFormat(new ProductFormat(format.externalId(), format.value(), format.packQuantity(),
                    format.sizeBucket(), format.reference(), index));
        }
    }

    private static <T> List<T> listOrEmpty(List<T> list) {
        return list == null ? List.of() : list;
    }

    enum Outcome { SKIPPED, ALREADY_APPLIED, APPLIED }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record Batch(String batch, List<CatalogSeeder.SeedProduct> additions,
                 List<Correction> corrections, List<Deactivation> deactivations,
                 List<Repricing> repricings, List<StockReset> unavailable,
                 List<ImageSet> imageSets) {}

    /** The photographs a new product should carry: its matched ones, or none. */
    @JsonIgnoreProperties(ignoreUnknown = true)
    record ImageSet(String sourceId, List<CatalogSeeder.SeedImage> images) {}

    /**
     * Supplier sale terms for a product. {@code expectedPrice} is the price it
     * had when the batch was prepared; any other current price means an
     * administrator repriced it, and it is then left alone.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    record Repricing(String sourceId, BigDecimal expectedPrice, BigDecimal price, SaleMode saleMode,
                     BigDecimal unitPrice, String unitLabel, String reference,
                     List<CatalogSeeder.SeedFormat> formats) {}

    /** A line the supplier marks "Rupture provisoire": stock 0, unless restocked since. */
    @JsonIgnoreProperties(ignoreUnknown = true)
    record StockReset(String sourceId, Integer expectedStock) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record Correction(String sourceId, String expectedNameFr, String expectedFormatValue, String nameFr, String nameEn,
                      String shortDescriptionFr, String shortDescriptionEn,
                      String descriptionFr, String descriptionEn,
                      String seoTitleFr, String seoTitleEn, String seoDescriptionFr, String seoDescriptionEn,
                      List<CatalogSeeder.SeedFormat> formats, List<ImageAlt> imageAlts) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record ImageAlt(String altFr, String altEn) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    record Deactivation(String sourceId, String expectedNameFr, String reason) {}
}
