// =============================================================================
// SELF-HOSTED WEB FONTS
//
// The stylesheet declared @font-face for Sora and Inter pointing at
// /fonts/*.woff2, and `public/fonts/` did not exist. Every request for them
// fell through to the Angular renderer, which answered with the HTML document —
// so the browser reported "OTS parsing error: invalid sfntVersion: 1008813135"
// (0x3C21444F, the bytes "<!DO") and silently fell back to Segoe UI. The site's
// entire typographic identity had never once rendered, on any page, for anyone.
//
// This downloads the two families from Google Fonts and writes them into
// public/fonts/ together with a generated @font-face partial. Self-hosting
// rather than linking to fonts.googleapis.com is deliberate: no third-party
// request on first paint, no render-blocking stylesheet on another origin, and
// nothing about the visitor handed to Google before they have asked for
// anything.
//
// Both families are licensed under the SIL Open Font License 1.1, which permits
// redistribution and self-hosting.
//
// Only the `latin` and `latin-ext` subsets are taken. The site is French and
// English; latin-ext is what carries œ, which French needs.
//
// Usage: node scripts/fetch-fonts.mjs
// =============================================================================

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(root, 'public', 'fonts');
const PARTIAL = path.join(root, 'src', 'styles', 'base', '_fonts.scss');

// A modern UA is required or the API serves TTF instead of WOFF2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Sora', query: 'Sora:wght@400..700', file: 'sora' },
  { name: 'Inter', query: 'Inter:wght@400..700', file: 'inter' },
];

const WANTED = new Set(['latin', 'latin-ext']);

/** Splits the Google CSS into blocks, each tagged with its subset comment. */
function parseFaces(css) {
  const faces = [];
  const pattern = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let match;
  while ((match = pattern.exec(css)) !== null) {
    const [, subset, block] = match;
    const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? 'normal';
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? '400';
    if (url && range) faces.push({ subset, url, range, style, weight });
  }
  return faces;
}

await mkdir(FONT_DIR, { recursive: true });

const declarations = [];

for (const family of FAMILIES) {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`;
  const css = await fetch(cssUrl, { headers: { 'User-Agent': UA } }).then((r) => r.text());

  const faces = parseFaces(css).filter((f) => WANTED.has(f.subset));
  if (faces.length === 0) {
    throw new Error(`no latin subsets found for ${family.name}`);
  }

  for (const face of faces) {
    const name = `${family.file}-${face.subset}.woff2`;
    const bytes = Buffer.from(
      await fetch(face.url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()),
    );

    // A WOFF2 file starts with the signature "wOF2". Anything else means the
    // download was an error page, which is precisely the failure this script
    // exists to fix — so it is checked rather than assumed.
    const signature = bytes.subarray(0, 4).toString('latin1');
    if (signature !== 'wOF2') {
      throw new Error(`${name} is not a WOFF2 file (signature "${signature}")`);
    }

    await writeFile(path.join(FONT_DIR, name), bytes);
    console.log(`  ${name.padEnd(24)} ${Math.round(bytes.length / 1024)} kB  (${face.subset})`);

    declarations.push(
      [
        '@font-face {',
        `  font-family: '${family.name}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${name}') format('woff2');`,
        `  unicode-range: ${face.range};`,
        '}',
      ].join('\n'),
    );
  }
}

const header = `// GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
//
// Self-hosted so the first paint depends on no third party. The families are
// variable and the weight range is declared, so one file per subset covers
// every weight the design uses.
//
// \`font-display: swap\` is deliberate: the fallback stack in _typography.scss is
// metrically close enough that swapping is less disruptive than blocking text.
`;

await writeFile(PARTIAL, `${header}\n${declarations.join('\n\n')}\n`);
console.log(`\nwrote ${path.relative(root, PARTIAL)} — ${declarations.length} faces`);
