// GENERATED by scripts/sync-monin-vinto.mjs from https://vinto.tn/49-monin.
// Source snapshot: 2026-09-10. Prices and stock are intentionally excluded.

import { Product } from '../shared/models/catalog.model';

const FAMILY = {
  "syrups": {
    "en": "MONIN syrup",
    "fr": "sirop MONIN"
  },
  "fruit-purees": {
    "en": "MONIN fruit purée",
    "fr": "purée de fruits MONIN"
  },
  "sauces": {
    "en": "MONIN gourmet sauce",
    "fr": "sauce gourmande MONIN"
  },
  "frappe-bases": {
    "en": "MONIN frappé base",
    "fr": "base frappé MONIN"
  },
  "bar-tools": {
    "en": "MONIN bar accessory",
    "fr": "accessoire de bar MONIN"
  }
} as const;

type MoninFamily = keyof typeof FAMILY;
type MoninSource = readonly [
  sourceId: string,
  slug: string,
  imageSlug: string,
  nameEn: string,
  nameFr: string,
  family: MoninFamily,
  format: string,
  featured: boolean,
];

const MONIN_SOURCE: readonly MoninSource[] = [
  ["162", "monin-sirop-sucre-de-canne-monin-1l-162", "sirop-sucre-de-canne-monin", "Syrup cane sugar MONIN 1 l", "Sirop sucre de canne MONIN 1L", "syrups", "1 l", true],
  ["164", "monin-sirop-saveur-rose-70cl-monin-164", "sirop-saveur-rose-70cl-monin", "Syrup rose MONIN 70 cl", "Sirop saveur rose 70cl MONIN", "syrups", "70 cl", true],
  ["165", "monin-concentre-lime-juice-cordial-70cl-monin-165", "concentre-lime-juice-cordial-70cl-monin", "Cordial lime juice cordial MONIN 70 cl", "Concentré lime juice cordial 70cl MONIN", "syrups", "70 cl", true],
  ["166", "monin-sirop-saveur-bubble-gum-70-cl-monin-166", "sirop-saveur-bubble-gum-70-cl-monin", "Syrup Bubble Gum MONIN 70 cl", "Sirop saveur bubble gum 70 cl MONIN", "syrups", "70 cl", true],
  ["170", "monin-sirop-saveur-coco-70cl-monin-170", "sirop-saveur-coco-70cl-monin", "Syrup coconut MONIN 70 cl", "Sirop saveur coco 70cl MONIN", "syrups", "70 cl", true],
  ["172", "monin-sirop-menthe-glaciale-monin-70cl-172", "sirop-menthe-glaciale-monin-70cl", "Syrup mint iced MONIN 70 cl", "Sirop menthe glaciale MONIN 70cl", "syrups", "70 cl", true],
  ["173", "monin-sirop-saveur-chocolat-blanc-monin-70cl-173", "sirop-saveur-chocolat-blanc-monin-70cl", "White syrup chocolate MONIN 70 cl", "Sirop saveur chocolat blanc MONIN 70cl", "syrups", "70 cl", true],
  ["175", "monin-sauce-caramel-monin-1-89l-175", "sauce-caramel-monin-189l", "Sauce caramel MONIN 1.89 l", "Sauce caramel MONIN 1,89L", "sauces", "1.89 l", true],
  ["177", "monin-sauce-au-chocolat-noir-monin-1-89l-177", "sauce-au-chocolat-noir-monin-189l", "Black sauce chocolate MONIN 1.89 l", "Sauce au chocolat noir MONIN 1,89L", "sauces", "1.89 l", false],
  ["266", "monin-le-fruit-kiwi-monin-1l-266", "le-fruit-kiwi-monin-1l", "Fruit purée kiwi MONIN 1 l", "Le fruit kiwi MONIN 1L", "fruit-purees", "1 l", false],
  ["271", "monin-le-fruit-pomme-granny-smith-monin-1l-271", "le-fruit-pomme-granny-smith-monin-1l", "Fruit purée granny smith apple MONIN 1 l", "Le fruit pomme granny smith MONIN 1L", "fruit-purees", "1 l", false],
  ["272", "monin-le-fruit-fruits-rouges-monin-1l-272", "le-fruit-fruits-rouges-monin-1l", "Fruit purée red berries MONIN 1 l", "Le fruit fruits rouges MONIN 1L", "fruit-purees", "1 l", false],
  ["280", "monin-frappe-vanille-monin-1-36kg-280", "frappe-vanille-monin-136kg", "Frappé base vanilla MONIN 1.36 kg", "Frappé vanille MONIN 1.36kg", "frappe-bases", "1.36 kg", false],
  ["282", "monin-frappe-cafe-monin-1-36kg-282", "frappe-cafe-monin-136kg", "Frappé base coffee MONIN 1.36 kg", "Frappé café MONIN 1.36kg", "frappe-bases", "1.36 kg", false],
  ["285", "monin-pompe-10ml-monin-285", "pompe-10ml-monin-pour-sirop-70cl", "Pump MONIN 10 ml", "Pompe 10ml MONIN.", "bar-tools", "10 ml", false],
  ["286", "monin-pompe-10ml-monin-286", "pompe-10ml-monin-pour-sirop-1l", "Pump MONIN 10 ml", "Pompe 10ml MONIN", "bar-tools", "10 ml", false],
  ["287", "monin-pompe-15ml-monin-287", "pompe-15ml-monin-pour-le-fruit-et-la-sauce", "Pump MONIN 15 ml", "Pompe 15ml MONIN", "bar-tools", "15 ml", false],
  ["288", "monin-doseur-metal-monin-288", "doseur-metal-30ml-60ml-monin", "Metal measure MONIN", "Doseur métal MONIN", "bar-tools", "", false],
  ["289", "monin-pilon-monin-289", "pilon", "Muddler MONIN", "Pilon MONIN", "bar-tools", "", false],
  ["290", "monin-rack-metal-4-bouteilles-monin-290", "rack-metal-4-bouteilles-monin", "Metal rack bottles 4 MONIN", "Rack métal 4 bouteilles MONIN", "bar-tools", "", false],
  ["293", "monin-barmat-293", "barmat", "Bar mat", "Barmat", "bar-tools", "", false],
  ["294", "monin-dispenser-en-verre-8-5l-avec-support-294", "dispenser-en-verre-85l-monin", "Dispenser glass stand 8.5 l", "Dispenser en verre 8.5L avec support", "bar-tools", "8.5 l", false],
  ["292", "monin-shaker-boston-monin-400ml-292", "shaker-boston-monin-400ml", "Shaker Boston MONIN 400 ml", "Shaker boston MONIN 400ml", "bar-tools", "400 ml", false],
  ["167", "monin-sirop-saveur-curacao-bleu-70cl-monin-167", "sirop-saveur-curacao-bleu-70cl-monin", "Blue syrup curaçao MONIN 70 cl", "Sirop Saveur Curaçao bleu 70cl MONIN", "syrups", "70 cl", false],
  ["295", "monin-sirop-peches-monin-70cl-295", "sirop-peches-monin-1l", "Syrup MONIN 70 cl", "Sirop pêches MONIN 70cl", "syrups", "70 cl", false],
  ["300", "monin-sirop-saveur-speculos-monin-70cl-300", "sirop-saveur-speculoos-monin-70cl", "Syrup speculoos MONIN 70 cl", "Sirop saveur spéculos MONIN 70cl", "syrups", "70 cl", false],
  ["301", "monin-sirop-pamplemousse-rose-monin-70cl-301", "sirop-pamplemousse-rose-monin-70cl", "Syrup rose MONIN 70 cl", "Sirop pamplemousse rose MONIN 70cl", "syrups", "70 cl", false],
  ["308", "monin-sirop-saveur-popcorn-monin-70cl-308", "sirop-saveur-popcorn-monin-70cl", "Syrup MONIN 70 cl", "Sirop saveur popcorn MONIN 70cl", "syrups", "70 cl", false],
  ["419", "monin-sirop-de-fraise-monin-25cl-419", "sirop-de-fraise-monin-25-cl", "Syrup strawberry MONIN 25 cl", "Sirop de Fraise Monin 25cl", "syrups", "25 cl", false],
  ["310", "monin-sirop-saveur-tiramisu-monin-70cl-310", "sirop-saveur-tiramisu-monin-70cl", "Syrup tiramisu MONIN 70 cl", "Sirop saveur tiramisu MONIN 70cl", "syrups", "70 cl", false],
  ["311", "monin-sirop-saveur-concombre-monin-70-cl-311", "sirop-saveur-concombre-monin-70-cl", "Syrup MONIN 70 cl", "Sirop saveur concombre MONIN 70 cl", "syrups", "70 cl", false],
  ["312", "monin-sirop-saveur-hibiscus-monin-70cl-312", "sirop-saveur-hibiscus-monin-70cl", "Syrup MONIN 70 cl", "Sirop saveur hibiscus MONIN 70cl", "syrups", "70 cl", false],
  ["318", "monin-sirop-saveur-gingembre-monin-70cl-318", "sirop-saveur-gingembre-monin-70cl", "Syrup MONIN 70 cl", "Sirop saveur gingembre MONIN 70cl", "syrups", "70 cl", false],
  ["320", "monin-sirop-grenadine-monin-70cl-320", "sirop-grenadine-monin-70cl", "Syrup grenadine MONIN 70 cl", "Sirop grenadine MONIN 70cl", "syrups", "70 cl", false],
  ["321", "monin-sirop-noisette-grillee-monin-70cl-321", "sirop-noisette-grillee-monin-70cl", "Syrup hazelnut MONIN 70 cl", "Sirop noisette grillée MONIN 70cl", "syrups", "70 cl", false],
  ["324", "monin-sirop-framboise-monin-70-cl-324", "sirop-framboise-monin-1l", "Syrup raspberry MONIN 70 cl", "Sirop framboise MONIN 70 cl", "syrups", "70 cl", false],
  ["325", "monin-sirop-mojito-mint-monin-1l-325", "sirop-mojito-mint-monin-70cl", "Syrup mojito mint MONIN 1 l", "Sirop mojito mint MONIN 1L", "syrups", "1 l", false],
  ["326", "monin-sirop-de-fraise-monin-1l-326", "sirop-de-fraise-monin-1l", "Syrup strawberry MONIN 1 l", "Sirop de fraise MONIN 1L", "syrups", "1 l", false],
  ["327", "monin-sirop-saveur-chocolat-monin-1l-327", "sirop-saveur-chocolat-monin-1l", "Syrup chocolate MONIN 1 l", "Sirop saveur chocolat MONIN 1L", "syrups", "1 l", false],
  ["331", "monin-sirop-pomme-verte-monin-70cl-331", "sirop-pomme-verte-monin-70cl", "Green syrup apple MONIN 70 cl", "Sirop pomme verte MONIN 70cl", "syrups", "70 cl", false],
  ["333", "monin-sirop-vanille-monin-1l-333", "sirop-vanille-monin-1l", "Syrup vanilla MONIN 1 l", "Sirop vanille MONIN 1L", "syrups", "1 l", false],
  ["335", "monin-sirop-the-citron-monin-70-cl-335", "sirop-the-citron-monin-1l", "Syrup lemon MONIN 70 cl", "Sirop thé citron MONIN 70 cl", "syrups", "70 cl", false],
  ["336", "monin-sirop-the-framboise-monin-70cl-336", "sirop-the-framboise-monin-70cl", "Syrup raspberry MONIN 70 cl", "Sirop thé framboise MONIN 70cl", "syrups", "70 cl", false],
  ["337", "monin-sirop-saveur-fleur-de-sureau-monin-70cl-337", "sirop-saveur-fleur-de-sureau-monin-70cl", "Syrup MONIN 70 cl", "Sirop saveur fleur de sureau MONIN 70cl", "syrups", "70 cl", false],
  ["363", "monin-cuillere-a-melange-monin-363", "ajout-cuill%C3%A8re-%C3%A0-m%C3%A9lange-monin", "Spoon mixing MONIN", "Cuillère à mélange MONIN", "bar-tools", "", false],
  ["421", "monin-sirop-grenadine-monin-25cl-421", "sirop-grenadine-monin-25cl", "Syrup grenadine MONIN 25 cl", "Sirop Grenadine Monin 25cl", "syrups", "25 cl", false],
  ["422", "monin-sirop-mojito-mint-monin-25cl-422", "sirop-mojito-mint-monin-25-cl", "Syrup mojito mint MONIN 25 cl", "Sirop Mojito Mint Monin 25cl", "syrups", "25 cl", false],
  ["425", "monin-sirop-noisette-monin-25cl-425", "sirop-noisette-grill%C3%A9e-monin-25cl", "Syrup hazelnut MONIN 25 cl", "Sirop Noisette Monin 25cl", "syrups", "25 cl", false],
  ["416", "monin-sirop-saveur-curacao-bleu-monin-25cl-416", "sirop-saveur-cura%C3%A7ao-bleu-monin-25-cl", "Blue syrup curaçao MONIN 25 cl", "Sirop Saveur Curaçao Bleu Monin 25cl", "syrups", "25 cl", false],
  ["447", "monin-coffret-sirops-pour-virgin-mojitos-447", "sirop-mojito-mint-monin-25-cl", "Coffret sirops pour virgin mojitos", "Coffret sirops pour virgin mojitos", "syrups", "", false],
  ["452", "monin-sirop-cerise-monin-70-cl-452", "sirop-cerise-monin-1l", "Syrup MONIN 70 cl", "Sirop cerise MONIN 70 cl", "syrups", "70 cl", false],
  ["453", "monin-doseur-metal-monin-453", "doseur-metal-30ml-60ml-monin", "Metal measure MONIN", "Doseur métal MONIN", "bar-tools", "", false],
  ["459", "monin-le-fruit-cassis-monin-1l-459", "le-fruit-framboise-monin-1l", "Fruit purée blackcurrant MONIN 1 l", "Le fruit cassis MONIN 1L", "fruit-purees", "1 l", false],
  ["464", "monin-sirop-mangue-monin-70-cl-464", "sirop-mangue-monin-1l", "Syrup MONIN 70 cl", "Sirop mangue MONIN 70 cl", "syrups", "70 cl", false],
  ["479", "monin-sirop-guimauve-grillee-monin-70cl-479", "sirop-guimauve-grillee-monin-70cl", "Syrup MONIN 70 cl", "Sirop Guimauve Grillee MONIN 70cl", "syrups", "70 cl", false],
  ["480", "monin-sirop-the-vert-matcha-monin-70cl-480", "sirop-noisette-grillee-monin-70cl", "Green syrup MONIN 70 cl", "Sirop The Vert Matcha MONIN 70cl", "syrups", "70 cl", false],
  ["482", "monin-sirop-mixeur-espresso-martini-monin-1l-482", "sirop-noisette-grillee-monin-70cl", "Syrup MONIN 1 l", "Sirop Mixeur Espresso Martini MONIN 1L", "syrups", "1 l", false],
];

export const MONIN_PRODUCTS: readonly Product[] = MONIN_SOURCE.map(
  ([sourceId, slug, imageSlug, nameEn, nameFr, family, format, featured]) => {
    const id = `p-monin-${sourceId}`;
    const label = FAMILY[family];
    const formatEn = format ? ` Format: ${format}.` : '';
    const formatFr = format ? ` Format : ${format}.` : '';
    const labelFr = label.fr.charAt(0).toUpperCase() + label.fr.slice(1);

    return {
      id,
      slug,
      name: { en: nameEn, fr: nameFr },
      shortDescription: {
        en: `${label.en} for professional bars, cafés, hotels and restaurants.${formatEn}`,
        fr: `${labelFr} pour les bars, cafés, hôtels et restaurants professionnels.${formatFr}`,
      },
      description: {
        en: `${nameEn} is part of our dedicated MONIN range.${formatEn} Availability, pack quantities and lead times are confirmed by our sales team on request.`,
        fr: `${nameFr} fait partie de notre univers MONIN.${formatFr} La disponibilité, les quantités par colis et les délais sont confirmés sur demande par notre équipe commerciale.`,
      },
      categoryId: 'monin',
      subcategoryId: family,
      brandId: 'monin',
      industries: ['restaurants', 'hotels', 'retail'],
      formats: format ? [{ id: `${id}-f1`, value: format }] : [],
      images: [{
        src: `/img/products/monin/${sourceId}-${imageSlug}.v2.webp`,
        alt: { en: `${nameEn} — product photograph`, fr: `${nameFr} — photographie du produit` },
        width: 800,
        height: 800,
      }],
      featured,
      seo: {
        title: { en: `${nameEn} | MONIN Tunisia`, fr: `${nameFr} | MONIN Tunisie` },
        description: {
          en: `${label.en} distributed in Tunisia by Société Ferid Khemakhem.`,
          fr: `${labelFr} distribué en Tunisie par la Société Ferid Khemakhem.`,
        },
      },
    } satisfies Product;
  },
);
