import { InjectionToken } from '@angular/core';

export interface SiteConfig {
  /** Canonical origin, without a trailing slash. Drives canonical + hreflang + sitemap. */
  readonly origin: string;
  readonly defaultOgImage: string;
  /** Same-origin endpoint that receives contact submissions. */
  readonly contactEndpoint: string;
  readonly newsletterEndpoint: string;
  /**
   * NEEDS_VERIFICATION: spam-protection site key. The secret half lives only in
   * a server env var. Left empty so the integration is wired but inert until the
   * owner provisions a key — never ship a hardcoded key.
   */
  readonly captchaSiteKey: string;
  /** Analytics is a placeholder: no third-party script loads until configured. */
  readonly analyticsId: string;
}

export const SITE_CONFIG = new InjectionToken<SiteConfig>('SITE_CONFIG', {
  providedIn: 'root',
  factory: (): SiteConfig => ({
    origin: 'https://www.catering.com.tn',
    // 1200x630 PNG — the size every social scraper expects. Generated by
    // `npm run art`; replace with a designed card when brand assets exist.
    defaultOgImage: '/img/og/default.png',
    contactEndpoint: '/api/contact',
    newsletterEndpoint: '/api/newsletter',
    captchaSiteKey: '',
    analyticsId: '',
  }),
});

/**
 * 301 map preserving the legacy site's link equity. Emitted into the hosting
 * rewrite configuration at build time by `scripts/generate-redirects.mjs`.
 */
export const LEGACY_REDIRECTS: Readonly<Record<string, string>> = {
  '/agro-alimentaire': '/fr/products/food',
  '/agro-alimentaire/': '/fr/products/food',
  '/produits-emballage': '/fr/products/packaging',
  '/produits-emballage/': '/fr/products/packaging',
  '/hygiene': '/fr/products/hygiene',
  '/hygiene/': '/fr/products/hygiene',
  '/produits': '/fr/products',
  '/produits/': '/fr/products',
  '/contact': '/fr/contact',
  '/contact/': '/fr/contact',
};
